# Generated by Django 4.2.2 on 2023-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='tb_mascotas',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Tipo de Noticia'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cuerpo',
            field=models.CharField(max_length=20, verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=10, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=10, null=True, verbose_name='Fecha publicación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Nombre del Periodista'),
        ),
    ]
