# Generated by Django 4.2.2 on 2023-07-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto_delete_tb_mascotas_alter_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cuerpo',
            field=models.CharField(max_length=150, verbose_name='Cuerpo'),
        ),
    ]
