# Generated by Django 4.2.2 on 2023-07-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('telefono', models.IntegerField(primary_key=True, serialize=False, verbose_name='telefono')),
                ('correo', models.CharField(max_length=50, verbose_name='correo')),
                ('mensaje', models.CharField(max_length=200, verbose_name='mensaje')),
            ],
        ),
    ]
